# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron Build ( Windows x64 )

env:
  GH_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- run: git submodule init
    #- run: git submodule update
    - run: xz --version
    - run: sudo apt update
    - run: sudo dpkg --add-architecture i386
    - run: sudo apt install wine64 libwine
    - run: wget -qO- https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -
    - run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv F987672F
    - run: sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
    - run: sudo apt-get install --install-recommends winehq-stable
    - run: npm install
    - run: npm run build:linux
    - name: Upload a Deploy Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          dist/*.exe
          dist/latest.yml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: dist
