# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo dpkg --add-architecture i386
    - run: wget -nc https://dl.winehq.org/wine-builds/winehq.key
    - run: sudo apt-key add winehq.key
    - run: sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ groovy main'
    - run: sudo apt update
    - run: sudo apt install --install-recommends winehq-stable
    - run: npm install
    - run: npm run publish
